# Use an official Python runtime as a base image
FROM python:3.11

# Install system dependencies (including PortAudio)
RUN apt-get update && apt-get install -y libportaudio2 libportaudio-dev

# Set the working directory inside the container
WORKDIR /app

# Copy all project files into the container
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install sounddevice

# Expose the Flask default port
EXPOSE 5000

# Command to run the application
CMD ["python", "main.py"]